max_trait_number = 1000000
initial_lifeforms_count = 10
population_limit = 50
logging_level = 'INFO'
initial_dna_chaos_chance = 10
initial_radiation = 0
led_brightness = 0.3
hat_model = "HD"
hat_simulator_size = 64, 64
hat_buffer_refresh_rate = 60
refresh_logic_link = True
